# Change prefix binding from C-b to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Makes windows 1 indexed
set -g base-index 1
setw -g pane-base-index 1

# Enables mouse mode
set -g mouse on

